aminya/project_options

.cmake-format.yaml
README.md
src/Index.cmake
src/Vcpkg.cmake
test/CMakeLists.txt

BREAKING CHANGE now, you should rename any usage of ProjectOptions to project_options
This was done for consistency with CMake's naming convention

fix: rename ProjectOptions to project_options

---

README.md
src/SystemLink.cmake

PUBLIC and INTERFACE mean that when the package is installed, the public/interface headers should be provided on the installed environment. This issue is not seen when a library is linked as private because during the installation, the headers are already built into the library.
Fixes #55

fix: use the cmake's include install directory for target_include_system_libraries

---

README.md
src/Index.cmake
src/StaticAnalyzers.cmake

Follow the same pattern used by MSVC/Clang/Cuda/GCC, to allow the user to override the flags passed to cppcheck.
Notes:
* This is not necessary or desired for clang-tidy because that is what the `.clang-tidy` configuration file is used for
* Unfortunately cppcheck does not provide the same kind top-level configuration file from what I can find.
* I am intentionally doing a full override of the options, not an addition, so we don't have to worry about conflicts

Make cppcheck flags configurable

---

src/DynamicProjectOptions.cmake

We should not expect the **average user** of a library pass flags to be able to use a library. Instead, **the developer** who knows the ins and outs of the library should set the developer mode to ON. 
This not only affects the average end-users but also the **advanced users** that should go through the whole dependency tree and pass flags to each of them to make them usable as a dependency.
I should have paid attention to this in #46, but it is still not late to fix the default.

fix: set ENABLE_DEVELOPER_MODE to OFF by default + report the building mode

---

src/Sanitizers.cmake

Before this commit having a falsly setup VSINSTALLDIR would not trigger the error. 
This had two reasons:
- first, the CMake string FIND module had the arguments mixed up
- second, the check itself never expanded the output variable from the string FIND
After this commit the error should be emitted if $VCINSTALLDIR is not in $PATH

fix: correctly check if vsinstalldir is in $path on msvc

---

README.md
src/DynamicProjectOptions.cmake

Many people use vcpkg
BREAKING CHANGE this requires adding `set(ENABLE_CONAN_DEFAULT ON)` before calling `dynamic_project_options`

fix: make Conan optional in dynamic_project_options

---

README.md
src/PackageProject.cmake
test/CMakeLists.txt

These are treated the same during installation, but accepting both removes confusion for the users

fix: accept INTERFACE_* as an alias to PUBLIC_* in package_project

---

src/CompilerWarnings.cmake

fix: remove non-C warnings for C

---

src/Utilities.cmake
src/VCEnvironment.cmake

refactor: make detect_architecture a generic utility function

---

src/Doxygen.cmake

Here are the release notes. I don't see any breaking changes that affect `project_options`.
https://github.com/jothepro/doxygen-awesome-css/releases/tag/v2.0.0
Thanks to @jothepro for making Doxygen awesome.
How it looks like for our tests:

feat: upgrade to doxygen-awesome-css v2.0.2

---

LICENSE.txt
README.md
test/CMakeLists.txt

After months of discussions behind the doors, I decided to move this project under my account as I do not want its future development to be limited to certain imposed conditions and use cases. There is no "one good way" to do things, and we should accept this if we want to improve things in the C++ ecosystem.
The development of `project_options` will be continued under the @aminya account without any change in the scope or features. All the contributions are still accepted thankfully. I might create a new organization to gather all my C++ projects in one place.

fix: transfer to aminya account

---

README.md
src/PackageProject.cmake

This has two benefits:
- Prevents any conflict if package_project is called multiple times
- Keeps the build directory cleaner

fix: use the project_name for the default export destination

---

src/Conan.cmake

Stumbled across this problem when using project options to build a library, that library could no longer be built via a conan recipe.
i have wrapped part of the conan.cmake to test if we are been built via ``conan`` and allow conan to define the build settings, rather than call ''conan_cmake_autodetect`` 
you can find my test project [library](https://github.com/lambtonr/conan_library) and [recipe](https://github.com/lambtonr/conan_recipe) that shows the problem (currently calling my fork of project options) reverting back to current release should show the following issue.
gcc ``conan create ./all 0.0.1@lambtonr/testing``
```sh
[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
[100%] Linking CXX executable bin/example
[100%] Built target example …
```

Allow project options to be used in creation of a conan package. 

---

src/Common.cmake

Previously this only fixed the immediate build scope and not the whole build

fix: set the fallbacks of the RelWithDebInfo Colcon build in the cache

---

src/MinGW.cmake

fix: typo in mingw.cmake

---

src/Conan.cmake

Invoking Conan with `-s build_type=` parameter matching active CMake build type, or all the active ones if in multi-config scenario.
This allows CMake to correctly build targets and link to correct Conan-insatlled dependencies.

Forcing Conan build type to match CMake one

---

src/Conan.cmake
src/Index.cmake
src/StaticAnalyzers.cmake
src/VCEnvironment.cmake

if to project **A** and **B** use different version of `project_options` and
project **C** use A and B with `CMP.cmake` (_FetchContents_), there is a common `CMakeCache` variable used!

prevent use of ProjectOptions_SRC_DIR as cache var

---

.github/workflows/ci.yml
src/Index.cmake
src/Optimization.cmake
src/PackageProject.cmake
src/SystemLink.cmake
test/CMakeLists.txt
test/include/mylib/lib.hpp
test/libs/mythirdpartylib/CMakeLists.txt
test/libs/mythirdpartylib/include/Foo.hpp
test/libs/mythirdpartylib/src/Foo.cpp
test/src/main/main.cpp
test/src/mylib2/lib.cpp
test_install/src/another_main.cpp

- 3.20 is required by the windows toolchain and cmake_path. It also has a more reliable building functionality.
- 3.18 required by package_project and interprocedural optimization. It also has a more reliable building functionality (no errors during the linking stage).
Installing a new CMake version is very easy using [setup-cpp](https://github.com/aminya/setup-cpp/) or other methods like `pip`

fix: require CMake 3.20 as the minimum version

---

src/Common.cmake

ProjectOptions_SRC_DIR is now cached as INTERNAL

---

src/Conan.cmake

Fix  #185 - make conancenter's remote name to match conan's default

---

src/Utilities.cmake

Added statements to detect when system processor is either riscv64 or riscv32  and put rv64 or rv32 respectively,  into the arch variable. This keeps these cases from falling through and accidentally picking up the x64 arch flags.

Added riscv architecture to Utilities.cmake

---

src/Conan.cmake
src/Index.cmake

Added additional variables with sensible defaults so that users may specify a host and/or build profile for the cmake_install_command. This is useful in cross compiling scenarios where the single profile argument is not enough.

Allow passing build and host profiles through to conan

---

src/Common.cmake

It helps clang based tools to find `compile_commands.json` when using out-of-source builds, and to find the correct `compile_commands.json` when handling multiple builds.
Already tested in my [FeignClaims/cmake_starter_template](https://github.com/FeignClaims/cmake_starter_template/tree/main/cmake) (for the orign extension version, see `cmake/SymlinkCompileCommands.cmake`) when I switch between clang and gcc on MacOS and Windows.
Users should be notified to add `compile_commands.json` to `.gitignore` though.

feat: create a symlink of `complie_commands.json` on the source dir

---

docs/src/target_disable_static_analysis.md
src/StaticAnalyzers.cmake

It looks like for the interface completeness there should be macro `target_disable_include_what_you_use`.
Since `iwyu` is also static analysis tool, I added call for this macro in `target_disable_static_analysis`

Add target disable macro for include-what-you-use

---

src/DynamicProjectOptions.cmake

With this change, `dynamic_project_options` now can handle also string and list options previously not exposed.
Now the only parameter of `project_options` not exposed as dynamic property is `PREFIX`, which is intrinsically bounded to value set during development.
With this pull request, all features covered by the closed  #208 request are now supported through `dynamic_project_options`.

Added support for all missing options to `dynamic_project_options`

---

src/CompilerWarnings.cmake

Most of the compiler flags are ignored by the linker, but some of them are used (especially when using LTO or using -Werror) , so just pass all of them.
Fixes #213

feat: Pass compiler warnings to the linker.

---

src/Hardening.cmake

Currently when using Clang on MacOS M1, enabling both `ENABLE_STACK_PROTECTION` and `WARNINGS_AS_ERRORS` prevents compilation:
```bash
clang-16: error: argument unused during compilation: '-fstack-clash-protection' [-Werror,-Wunused-command-line-argument]
```
That is, the `-fstack-clash-protection` part (currently) isn't supported on this environment. Since the `-fstack-protector-strong` part in `ENABLE_STACK_PROTECTION` works, I propose to fix the option instead of requiring users to disable it.

fix: Disable `-fstack-clash-protection` on MacOS M1 when using Clang

---

src/CompilerWarnings.cmake

When using a project with only C as the selected language, the following warning will appear:
```
CMake Warning (dev) at cmake-build-debug/_deps/_project_options-src/src/CompilerWarnings.cmake:107 (message):
No compiler warnings set for CXX compiler: ''
```
This happens because `CMAKE_CXX_COMPILER_ID` is not set, only `CMAKE_C_COMPILER_ID` is, there are other bugs related to this behavior but they don't produce warnings.

fix: Don't fail to set warnings when only using the C language.

---

docker/Dockerfile.mingw

> After adding cross-compiler to setup-cpp, update [Dockerfile.mingw](https://github.com/abeimler/project_options/blob/feature/toolchains/docker/Dockerfile.mingw#L16) so setup-cpp can install the cross-compiler (MinGW)
https://github.com/aminya/project_options/issues/180

install mingw with setup-cpp

---

src/Vcpkg.cmake

This speeds up the CMake configuration time when vcpkg is updated recently.

feat: skip vcpkg updates if updated recently

---

src/Git.cmake

In some cases, the directory might exist but not be there because of another git process cloning. This timeout allows cloning in that directory. Git will error out with more information if it fails.

fix: force cloning if the directory exists in `git_clone` function

---

.github/workflows/ci.yml
README.md
docs/src/Readme_top.md
docs/src/project_options_example.md
src/Conan.cmake
src/DynamicProjectOptions.cmake
src/Index.cmake
tests/install/CMakeLists.txt
tests/install/conanfile.txt
tests/myproj/CMakeLists.txt
tests/myproj/conanfile.txt

Support conan 2 by replacing the old conan script with [`conan_provider.cmake`](https://github.com/conan-io/cmake-conan/blob/develop2/conan_provider.cmake).
Todo:
Current design questions:
- The new `conan_provider.cmake` script for conan 2 requires CMake 2.24+. Is it acceptable to set `cmake_minimum_required(VERSION 3.24)` for the whole project_options?
- The cmake script for conan 2 is incompatible with conan 1. Should I keep the conan 1 function or replace it?
Close #212

feat: support conan 2

---

src/PackageProject.cmake
src/SystemLink.cmake
src/Utilities.cmake
tests/myproj/CMakeLists.txt

Add a function `convert_genex_semicolons` to convert semicolons inside generator expressions into `$<SEMICOLON>`. After this function, the list contains generator expressions can be properly iterated.
```cmake
set(dirs "$<$<CONFIG:Debug>:dir1;dir2>" "$<$<CONFIG:Release>:dir3;dir4>")
convert_genex_semicolons("${dirs}" dirs)
foreach(dir IN LISTS dirs)
endforeach()
```
Close #205

fix: support iterating list containing generator expressions that have semicolons

---

.github/workflows/ci.yml
src/DynamicProjectOptions.cmake
src/Sanitizers.cmake
src/Utilities.cmake
tests/install/CMakeLists.txt
tests/myproj/CMakeLists.txt
tests/myproj/Taskfile.yml

According to [this comment](https://github.com/orgs/Homebrew/discussions/3384#discussioncomment-6264292), gcc now dosen't support libsanitizer on macOS with arm64 and macOS Ventuna or later with x86_64.

fix: Disable gcc sanitizer on macos by default

---

src/Sanitizers.cmake

When configuring for MSVC Address Sanitizer was no longer enabled by default, this is due to the detection check being inverted
Fixes #265

fix(MSVC): Address Sanitizer detection logic is inverted

---

src/Hardening.cmake
src/Index.cmake
src/Optimization.cmake

fix #259 by using generator expressions and `CMAKE_INTERPROCEDURAL_OPTIMIZATION_<CONFIG>`.

fix: fix Hardening options and LTO for multi-configuration generators

---

src/Index.cmake

set [`CMP0137`](https://cmake.org/cmake/help/latest/policy/CMP0137.html) to `NEW` if cmake >= 3.24.
Fixes #267.

fix: Enable policy 137 for check_ipo_supported()

---

src/Index.cmake
src/Sanitizers.cmake

With the current implementation if CMAKE_MSVC_DEBUG_INFORMATION_FORMAT is set, it won't be respected as the /Zi flag set on enable_sanitizers will always override it, just skip setting it if POLICY CMP0141 is available, if the user has set CMAKE_MSVC_DEBUG_INFORMATION_FORMAT to EditAndContinue, than only in that case override it.
Fixes #262

fix(MSVC): Don't enforce /Zi if POLICY CMP0141 is available

---

.github/workflows/ci.yml
src/Hardening.cmake
tests/myproj/CMakeLists.txt

Build failed on [(macos-12, clang-15, release, developer_mode (warnings_as_errors))](https://github.com/FeignClaims/cpp_conan_template/actions/runs/10350621313/job/28647441558#step:8:198) because of
```txt
error: '_FORTIFY_SOURCE' macro redefined [clang-diagnostic-macro-redefined,-warnings-as-errors]
```
After some research, I noticed both [this guide](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C%2B%2B.md) and [firefox](https://searchfox.org/mozilla-central/source/build/moz.configure/toolchain.configure#2898-2903) recommend/use `-U_FORTIFY_SOURCE` before `-D_FORTIFY_SOURCE=3` to avoid this problem, So I suggest to fix this issue in this way.

fix: undef _FORTIFY_SOURCE before setting

---

.github/workflows/ci.yml
src/Standards.cmake
tests/install/CMakeLists.txt
tests/myproj/CMakeLists.txt

Some tools in different platforms do not support C++ 23 (e.g. gcc on MacOS)

fix: remove C++/C 23 until officially released

---

src/StaticAnalyzers.cmake

We provide no way to explicitly and separately (without changing `CMAKE_<LANG>_STANDARD`) specify what standard cppcheck should use. Therefore, when cppcheck fallbacking to use the default standard, the corresponding cmake message should be `STATUS` instead of `${WARNING_MESSAGE}` which fails the compilation when `WARNINGS_AS_ERRORS`.

fix: correct message level for cppcheck fallback standard

---

src/Conan.cmake

This makes conan in cmake more transparent.

feat: allow system package installation for conan by default
