aminya/project_options

- README.md
- src/CompilerWarnings.cmake
- src/Index.cmake
- Expose options for compiler warnings
> Option for Compiler Warnings

- src/Sanitizers.cmake
- src/StandardProjectSettings.cmake
- src/Utilities.cmake
- src/VCEnvironment.cmake
This automatically finds `vcvarsall` and then runs it in a process. It parses the output and sets the environment variables inside CMake.
This fixes so many issues. Such as:
- using MSVC with Ninja
- building Qt
- building Cuda
- .....
> Automatically set-up MSVC environment via vcvarsall

- src/Conan.cmake
Closes https://github.com/cpp-best-practices/cpp_starter_project/pull/122
Fixes https://github.com/cpp-best-practices/cpp_starter_project/issues/40
> fix: pass CC and CXX to conan

- src/Conan.cmake
Cherry-picked from https://github.com/cpp-best-practices/cpp_starter_project/pull/175/
> fix: update cmake-conan

- src/Vcpkg.cmake
Fixes some bugs in the automatic installation of vcpkg and also automatic updating of the repository.
> fix: bug fixes in run_vcpkg function

- .clang-tidy
- src/StaticAnalyzers.cmake
- test/main.cpp
Related to https://github.com/MarkSchofield/Toolchain/issues/12
> fix: handle clang-tidy in clang-cl mode

- src/Index.cmake
> fix: accept multiple warnings

- src/StandardProjectSettings.cmake
- src/Standards.cmake
- test/CMakeLists.txt
> feat: turn off CMAKE_CXX_EXTENSIONS by default + default the C standard to the latest

- src/Common.cmake
Based on
https://github.com/cpp-best-practices/cpp_boilerplate_project/blob/f37c1abad41705630ddf3a48aec7b6fa17209423/CMakeLists.txt#L52-L72
> feat: add multi-config handling

- cspell.config.yaml
- src/Conan.cmake
- src/PackageProject.cmake
- src/VCEnvironment.cmake
Based on
https://github.com/cpp-best-practices/cpp_boilerplate_project/blob/f37c1abad41705630ddf3a48aec7b6fa17209423/CMakeLists.txt#L125-L130
> feat: put the executable on PATH for debugging inside Visual Studio

- src/VCEnvironment.cmake
https://github.com/MarkSchofield/Toolchain/pull/33
> fix: update MSVC toolchain

- README.md
- src/DynamicProjectOptions.cmake
- src/Index.cmake
- src/Linker.cmake
BREAKING CHANGE removes the global USER_LINKER_OPTION variable
> feat: add the LINKER option to project_options

- src/VCEnvironment.cmake
> fix: fix vcvarsall not working when it is verbose (inside Visual Studio)

- README.md
- src/Index.cmake
> feat: support multi-project projects by adding PREFIX

- src/CompilerWarnings.cmake
> Warn about semicolon after in-class function definition

- src/SystemLink.cmake
> Enable SYSTEM includes when supported on WIN32

- src/VCEnvironment.cmake
> fix: update the windows toolchain to v0.5.1

- src/PackageProject.cmake
Following up on https://github.com/polysquare/cmake-forward-arguments/issues/5
> fix: update cmake-forward-arguments to v1.0.0

- .github/workflows/ci.yml
- src/Index.cmake
> fix: set the policy for fetch content in Cmake 3.24

- src/CompilerWarnings.cmake
> fix: remove -Wextra-semi for C

- .github/workflows/ci.cross.arm.yml
- docker/Dockerfile.arm
> fatal error: stdio.h: No such file or directory
> fix: cross arm C build

- src/VCEnvironment.cmake
> fix: update the MSVC toolchain to v0.6.0

- src/DynamicProjectOptions.cmake
This merge requests aims to resolve bug #111 .
> Allow command line override of `dynamic_options`

- src/StaticAnalyzers.cmake
Currently clang-tidy will fail to run if using GCC with a target different from the host, this modification allows us to extract the default target and sysroot from a GCC compiler in order to feed it to clang-tidy.
> feat: Support the usage of clang-tidy when cross compiling with GCC.

- src/Index.cmake
> fix: do not include the MSVC toolchain if CMAKE_TOOL_CHAIN is specified

- src/CrossCompiler.cmake
- src/PackageProject.cmake
> fix(cmake): Replace deprecated `FetchContent_Populate`
